### ISSUE TITLE
Buscando encontre este editor bootstrap compatible que tiene pinta...

### ISSUE THREAD

**Issue by Together-Robots** [germg/TpFinalWeb2#1]
[ALTO EDITOR DE TEXTO RICO](http://summernote.org/getting-started/
)
en vez del otro que tenía problemas con el jquery este puede ir.

> No me pude dormir de lo pasado q estoy....mira la hora que es....

**Comment by germg** [comment]
muy bueno, vamos con este!


*Saludos cordiales.*

*Germán Mazza Gentile*

2016-06-24 5:21 GMT-03:00 Tbots <notifications@github.com>:
