### ISSUE TITLE
Para incluir Maps en artitulo

### ISSUE THREAD

**Issue by Together-Robots** [germg/TpFinalWeb2#2]
[esta forma](http://stackoverflow.com/questions/1726049/how-do-you-click-on-a-map-and-have-latitude-and-longitude-fields-in-a-form-popul) encontre para obtener la lat y long de un click en el mapa...
voy a tratar de implementarla a la brevedad.

**Comment by germg** [comment]
Genial, lo podemos usar para la registración del cliente tmb. Lo estaba
dejando para mas adelante, si lo sacas ya lo metemos.


*Saludos cordiales.*

*Germán Mazza Gentile*

2016-06-27 16:16 GMT-03:00 Tbots <notifications@github.com>:
